/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.directed-graph .edge {\n  stroke: #666;\n  fill: none; }\n\n.directed-graph .panning-rect {\n  fill: transparent;\n  cursor: move; }\n\n.directed-graph .node-group {\n  transition: 0.5s ease-in-out; }\n'];