/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.directed-graph {\n  user-select: none; }\n  .directed-graph .edge {\n    stroke: #666;\n    fill: none; }\n    .directed-graph .edge .edge-label {\n      stroke: none;\n      font-size: 12px;\n      fill: #ffffff; }\n  .directed-graph .panning-rect {\n    fill: transparent;\n    cursor: move; }\n  .directed-graph .node-group .node:focus {\n    outline: none; }\n'];