/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../build/directed-graph/mouse-wheel.directive';
import * as import1 from '@angular/core/src/linker/view';
export class Wrapper_MouseWheelDirective {
  /*private*/ _eventHandler:Function;
  context:import0.MouseWheelDirective;
  /*private*/ _changed:boolean;
  subscription0:any;
  subscription1:any;
  constructor() {
    this._changed = false;
    this.context = new import0.MouseWheelDirective();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
    (this.subscription0 && this.subscription0.unsubscribe());
    (this.subscription1 && this.subscription1.unsubscribe());
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    if ((eventName == 'mousewheel')) {
      const pd_sub_0:any = ((<any>this.context.onMouseWheelChrome($event)) !== false);
      result = (pd_sub_0 && result);
    }
    if ((eventName == 'DOMMouseScroll')) {
      const pd_sub_1:any = ((<any>this.context.onMouseWheelFirefox($event)) !== false);
      result = (pd_sub_1 && result);
    }
    if ((eventName == 'onmousewheel')) {
      const pd_sub_2:any = ((<any>this.context.onMouseWheelIE($event)) !== false);
      result = (pd_sub_2 && result);
    }
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any,emit0:boolean,emit1:boolean):void {
    this._eventHandler = _eventHandler;
    if (emit0) { (this.subscription0 = this.context.mouseWheelUp.subscribe(_eventHandler.bind(view,'mouseWheelUp'))); }
    if (emit1) { (this.subscription1 = this.context.mouseWheelDown.subscribe(_eventHandler.bind(view,'mouseWheelDown'))); }
  }
}